language: python
python:
  - "3.7"
  # command to install dependencies
install:
  - pip install pytest
  - pip install coverage
  - pip install coveralls
  - pip install -e .
# command to run tests
script:
  - pytest ./tests
  - coverage run --omit=performance_test.ipynb
after_success:
  - coveralls
